const SESSION_MS = 7 * 86400000;
const enc = new TextEncoder();
const str = (v, n = 100) => String(v ?? '').trim().slice(0, n);
const now = () => Date.now();
const uid = () => crypto.randomUUID();
async function digest(value) { const b = await crypto.subtle.digest('SHA-256', enc.encode(value)); return [...new Uint8Array(b)].map(x => x.toString(16).padStart(2, '0')).join(''); }
async function secretHash(pin) { const salt = crypto.randomUUID().replaceAll('-', ''); return `sha256:${salt}:${await digest(`${salt}:${pin}`)}`; }
async function secretMatches(pin, stored) { if (!stored) return false; if (stored.startsWith('plain:')) return pin === stored.slice(6); const [, salt, hash] = stored.split(':'); return !!salt && hash === await digest(`${salt}:${pin}`); }
function json(data, status = 200, extra = {}) { return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...extra } }); }
function fail(message, status = 400) { throw Object.assign(new Error(message), { status }); }
function body(req) { return req.json().catch(() => fail('ข้อมูลไม่ถูกต้อง')); }
function phone(v) { const p = str(v, 30).replace(/[^0-9]/g, ''); if (!/^0\d{9}$/.test(p)) fail('เบอร์โทรต้องมี 10 หลักขึ้นต้นด้วย 0'); return p; }
function email(v) { const e = str(v, 254).toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)) fail('อีเมลไม่ถูกต้อง'); return e; }
function pin(v) { const p = str(v, 20); if (!/^\d{4,12}$/.test(p)) fail('PIN ต้องเป็นตัวเลข 4–12 หลัก'); return p; }
function color(v) { const c = str(v, 7); if (!/^#[\da-f]{6}$/i.test(c)) fail('สีไม่ถูกต้อง'); return c; }
const cleanPrefix = v => str(v, 30).replace(/[^A-Za-z0-9-]/g, '').slice(0, 24) || 'BOBA-';
async function q(db, sql, ...args) { return db.prepare(sql).bind(...args); }
async function one(db, sql, ...args) { return (await q(db, sql, ...args)).first(); }
async function all(db, sql, ...args) { const result = await (await q(db, sql, ...args)).all(); return result.results || []; }
function token(req) { return /(?:^|;\s*)boba_session=([^;]*)/.exec(req.headers.get('cookie') || '')?.[1] || ''; }
async function session(req, env) { const t = token(req); if (!t) return null; const s = await one(env.DB, 'SELECT * FROM sessions WHERE token_hash=? AND expires_at>?', await digest(t), now()); if (!s) return null; return s; }
async function auth(req, env, role) { const s = await session(req, env); if (!s || s.role !== role) fail('กรุณาเข้าสู่ระบบ', 401); return s; }
async function setSession(role, subject, env) { const raw = crypto.randomUUID() + crypto.randomUUID(); await env.DB.prepare('INSERT INTO sessions (token_hash,role,subject_id,expires_at) VALUES (?,?,?,?)').bind(await digest(raw), role, subject, now() + SESSION_MS).run(); return `boba_session=${raw}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${SESSION_MS / 1000}`; }
function safeShop(s) { if (!s) return null; const { pin_hash, ...rest } = s; return rest; }
async function memberView(id, env) { const m = await one(env.DB, 'SELECT * FROM members WHERE id=?', id); if (!m) fail('ไม่พบสมาชิก', 404); const s = await one(env.DB, 'SELECT * FROM shops WHERE id=?', m.shop_id); const events = await all(env.DB, 'SELECT kind,points,note,created_at FROM events WHERE member_id=? ORDER BY id DESC LIMIT 30', id); return { member: m, shop: safeShop(s), events }; }
async function merchantView(id, env) { const s = await one(env.DB, 'SELECT * FROM shops WHERE id=?', id); return { shop: safeShop(s), members: await all(env.DB, 'SELECT id,name,phone,email,stamps,status,created_at FROM members WHERE shop_id=? ORDER BY created_at DESC', id), events: await all(env.DB, 'SELECT member_name,kind,points,note,created_at FROM events WHERE shop_id=? ORDER BY id DESC LIMIT 30', id) }; }
async function adminView(env) { return { shops: await all(env.DB, `SELECT s.id,s.name,s.branch,s.owner,s.phone,s.plan,s.status,s.member_prefix,s.theme_primary,s.card_title,s.card_note,s.reward_text,s.created_at,COUNT(m.id) member_count,COALESCE(SUM(m.stamps),0) stamp_count FROM shops s LEFT JOIN members m ON m.shop_id=s.id GROUP BY s.id ORDER BY s.created_at DESC`), members: await all(env.DB, 'SELECT id,shop_id,name,phone,email,stamps,status,created_at FROM members ORDER BY created_at DESC') }; }
async function api(req, env, path) {
  const method = req.method;
  if (method === 'GET' && path === '/api/health') return json({ ok: true, database: 'cloudflare-d1' });
  if (method === 'GET' && path === '/api/shops') return json({ shops: await all(env.DB, "SELECT id,name,branch,theme_primary FROM shops WHERE status='active' ORDER BY name"), devOtp: env.DEV_OTP === '1' });
  if (method === 'GET' && path === '/api/session') return json({ role: (await session(req, env))?.role || null });
  if (method === 'POST' && path === '/api/logout') { const t = token(req); if (t) await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(t)).run(); return json({ ok: true }, 200, { 'set-cookie': 'boba_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0' }); }
  if (method === 'POST' && path === '/api/customer/request-code') { const x = await body(req), purpose = x.purpose, sid = str(x.shopId, 80), p = phone(x.phone), s = await one(env.DB, 'SELECT * FROM shops WHERE id=? AND status=\'active\'', sid); if (!s) fail('ร้านนี้ยังไม่เปิดรับสมาชิก'); if (!['register', 'login'].includes(purpose)) fail('เลือกสมัครหรือเข้าสู่ระบบ'); const existing = await one(env.DB, 'SELECT * FROM members WHERE shop_id=? AND phone=?', sid, p); if (purpose === 'register' && existing) fail('เบอร์นี้สมัครแล้ว กรุณาเข้าสู่ระบบ', 409); if (purpose === 'login' && (!existing || existing.status !== 'active')) fail('ไม่พบสมาชิกในร้านนี้', 404); const name = purpose === 'register' ? str(x.name, 100) : existing.name; if (name.length < 2) fail('กรุณากรอกชื่ออย่างน้อย 2 ตัวอักษร'); const mail = purpose === 'register' ? email(x.email) : existing.email; const code = String(Math.floor(100000 + Math.random() * 900000)); if (env.DEV_OTP !== '1') { if (!env.OTP_WEBHOOK_URL) fail('ยังไม่ได้ตั้งค่าการส่ง OTP', 503); await fetch(env.OTP_WEBHOOK_URL, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${env.OTP_WEBHOOK_TOKEN || ''}` }, body: JSON.stringify({ to: mail, subject: 'รหัสยืนยัน Boba Stamp', text: `รหัสยืนยัน: ${code} (ใช้ได้ 5 นาที)` }) }); } const challenge = uid(); await env.DB.prepare('DELETE FROM challenges WHERE shop_id=? AND phone=?').bind(sid, p).run(); await env.DB.prepare('INSERT INTO challenges (id,purpose,shop_id,phone,email,name,code_hash,expires_at,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(challenge, purpose, sid, p, mail, name, await digest(code), now() + 300000, now()).run(); return json({ challengeId: challenge, email: mail.replace(/^(.{1,2}).*(@.*)$/, '$1***$2'), expiresIn: 300, ...(env.DEV_OTP === '1' ? { devCode: code } : {}) }); }
  if (method === 'POST' && path === '/api/customer/verify') { const x = await body(req), c = await one(env.DB, 'SELECT * FROM challenges WHERE id=?', str(x.challengeId, 80)); if (!c || c.expires_at < now()) fail('รหัสหมดอายุ กรุณาขอใหม่'); if (await digest(str(x.code, 8)) !== c.code_hash) fail('รหัสไม่ถูกต้อง'); let m = await one(env.DB, 'SELECT * FROM members WHERE shop_id=? AND phone=?', c.shop_id, c.phone); if (c.purpose === 'register' && !m) { const s = await one(env.DB, 'SELECT * FROM shops WHERE id=?', c.shop_id); const id = cleanPrefix(s.member_prefix) + crypto.randomUUID().replaceAll('-', '').slice(0, 8).toUpperCase(); await env.DB.prepare('INSERT INTO members (id,shop_id,name,phone,email,created_at) VALUES (?,?,?,?,?,?)').bind(id, c.shop_id, c.name, c.phone, c.email, now()).run(); m = await one(env.DB, 'SELECT * FROM members WHERE id=?', id); } if (!m || m.status !== 'active') fail('สมาชิกนี้ใช้งานไม่ได้'); await env.DB.prepare('DELETE FROM challenges WHERE id=?').bind(c.id).run(); return json({ ok: true }, 200, { 'set-cookie': await setSession('member', m.id, env) }); }
  if (method === 'GET' && path === '/api/member') return json(await memberView((await auth(req, env, 'member')).subject_id, env));
  if (method === 'POST' && path === '/api/member/qr') { const s = await auth(req, env, 'member'), raw = crypto.randomUUID() + crypto.randomUUID(); await env.DB.prepare('DELETE FROM qr_tokens WHERE member_id=?').bind(s.subject_id).run(); await env.DB.prepare('INSERT INTO qr_tokens (token_hash,member_id,expires_at) VALUES (?,?,?)').bind(await digest(raw), s.subject_id, now() + 60000).run(); return json({ token: raw, expiresIn: 60 }); }
  if (method === 'POST' && path === '/api/merchant/login') { const x = await body(req), s = await one(env.DB, 'SELECT * FROM shops WHERE phone=? AND status=\'active\'', phone(x.phone)); if (!s || !(await secretMatches(pin(x.pin), s.pin_hash))) fail('เบอร์ร้านหรือ PIN ไม่ถูกต้อง หรือร้านยังไม่เปิดใช้งาน', 401); return json({ ok: true }, 200, { 'set-cookie': await setSession('merchant', s.id, env) }); }
  if (method === 'GET' && path === '/api/merchant') return json(await merchantView((await auth(req, env, 'merchant')).subject_id, env));
  if (method === 'POST' && ['/api/merchant/stamp', '/api/merchant/redeem'].includes(path)) { const s = await auth(req, env, 'merchant'), x = await body(req), id = str(x.memberId, 80), redeem = path.endsWith('/redeem'), m = await one(env.DB, 'SELECT * FROM members WHERE id=? AND shop_id=? AND status=\'active\'', id, s.subject_id); if (!m) fail('ไม่พบสมาชิกของร้านนี้', 404); if (redeem && m.stamps < 10) fail('แต้มยังไม่ครบ 10'); if (!redeem && m.stamps >= 10) fail('แต้มครบ 10 แล้ว กรุณาแลกรางวัลก่อน'); if (x.qrToken) { const qx = await one(env.DB, 'SELECT * FROM qr_tokens WHERE token_hash=? AND member_id=?', await digest(str(x.qrToken, 100)), id); if (!qx || qx.used_at || qx.expires_at < now()) fail('QR หมดอายุหรือถูกใช้แล้ว'); const qrUpdate = await env.DB.prepare('UPDATE qr_tokens SET used_at=? WHERE token_hash=? AND used_at IS NULL').bind(now(), qx.token_hash).run(); if (!qrUpdate.meta?.changes) fail('QR หมดอายุหรือถูกใช้แล้ว'); } const points = redeem ? -10 : 1, guard = redeem ? 'stamps>=10' : 'stamps<10'; const update = await env.DB.prepare(`UPDATE members SET stamps=stamps+? WHERE id=? AND ${guard}`).bind(points, id).run(); if (!update.meta?.changes) fail(redeem ? 'แต้มยังไม่ครบ 10' : 'แต้มครบ 10 แล้ว กรุณาแลกรางวัลก่อน'); await env.DB.prepare('INSERT INTO events (shop_id,member_id,member_name,kind,points,note,created_at) VALUES (?,?,?,?,?,?,?)').bind(s.subject_id, id, m.name, redeem ? 'redeem' : 'stamp', points, redeem ? (await one(env.DB, 'SELECT reward_text FROM shops WHERE id=?', s.subject_id)).reward_text : str(x.note, 120), now()).run(); return json({ member: await one(env.DB, 'SELECT * FROM members WHERE id=?', id) }); }
  if (method === 'PATCH' && path === '/api/merchant/theme') { const s = await auth(req, env, 'merchant'), x = await body(req); await env.DB.prepare('UPDATE shops SET theme_primary=?,card_title=?,card_note=?,reward_text=?,member_prefix=? WHERE id=?').bind(color(x.primary), str(x.title, 60), str(x.note, 140), str(x.reward, 100), cleanPrefix(x.prefix), s.subject_id).run(); return json({ shop: safeShop(await one(env.DB, 'SELECT * FROM shops WHERE id=?', s.subject_id)) }); }
  if (method === 'POST' && path === '/api/admin/login') { const x = await body(req), setting = await one(env.DB, "SELECT value FROM settings WHERE key='admin_pin_hash'"); const configured = env.ADMIN_PIN ? (env.ADMIN_PIN.startsWith('sha256:') || env.ADMIN_PIN.startsWith('plain:') ? env.ADMIN_PIN : `plain:${env.ADMIN_PIN}`) : (setting?.value || ''); const ok = await secretMatches(pin(x.pin), configured); if (!ok) fail('PIN ผู้ดูแลไม่ถูกต้อง', 401); return json({ ok: true }, 200, { 'set-cookie': await setSession('admin', 'admin', env) }); }
  if (method === 'GET' && path === '/api/admin') { await auth(req, env, 'admin'); return json(await adminView(env)); }
  const sm = /^\/api\/admin\/shops\/([^/]+)$/.exec(path), mm = /^\/api\/admin\/members\/([^/]+)$/.exec(path);
  if (method === 'PATCH' && sm) { await auth(req, env, 'admin'); const id = decodeURIComponent(sm[1]), x = await body(req), old = await one(env.DB, 'SELECT * FROM shops WHERE id=?', id); if (!old) fail('ไม่พบร้าน', 404); const values = [str(x.name ?? old.name), str(x.branch ?? old.branch), str(x.owner ?? old.owner), x.phone === undefined ? old.phone : phone(x.phone), x.pin ? await secretHash(pin(x.pin)) : old.pin_hash, str(x.plan ?? old.plan, 30), ['pending', 'active', 'banned'].includes(x.status) ? x.status : old.status, cleanPrefix(x.prefix ?? old.member_prefix), x.primary ? color(x.primary) : old.theme_primary, str(x.title ?? old.card_title, 60), str(x.note ?? old.card_note, 140), str(x.reward ?? old.reward_text, 100), id]; await env.DB.prepare('UPDATE shops SET name=?,branch=?,owner=?,phone=?,pin_hash=?,plan=?,status=?,member_prefix=?,theme_primary=?,card_title=?,card_note=?,reward_text=? WHERE id=?').bind(...values).run(); return json({ shop: safeShop(await one(env.DB, 'SELECT * FROM shops WHERE id=?', id)) }); }
  if (method === 'DELETE' && sm) { await auth(req, env, 'admin'); const id = decodeURIComponent(sm[1]); if ((await one(env.DB, 'SELECT COUNT(*) n FROM members WHERE shop_id=?', id)).n) fail('ร้านนี้มีสมาชิก กรุณาระงับแทนการลบ', 409); await env.DB.prepare('DELETE FROM shops WHERE id=?').bind(id).run(); return json({ ok: true }); }
  if (method === 'PATCH' && mm) { await auth(req, env, 'admin'); const id = decodeURIComponent(mm[1]), x = await body(req); if (!['active', 'banned'].includes(x.status)) fail('สถานะสมาชิกไม่ถูกต้อง'); await env.DB.prepare('UPDATE members SET status=? WHERE id=?').bind(x.status, id).run(); return json({ member: await one(env.DB, 'SELECT * FROM members WHERE id=?', id) }); }
  if (method === 'DELETE' && mm) { await auth(req, env, 'admin'); await env.DB.prepare('DELETE FROM members WHERE id=?').bind(decodeURIComponent(mm[1])).run(); return json({ ok: true }); }
  if (method === 'POST' && path === '/api/admin/shops') { await auth(req, env, 'admin'); const x = await body(req), p = phone(x.phone); const id = `shop-${uid()}`; await env.DB.prepare("INSERT INTO shops (id,name,branch,owner,phone,pin_hash,plan,status,member_prefix,created_at) VALUES (?,?,?,?,?,?,?,'pending',?,?)").bind(id, str(x.name), str(x.branch), str(x.owner), p, await secretHash(pin(x.pin)), str(x.plan, 30) || 'Trial', cleanPrefix(x.prefix), now()).run(); return json({ shop: safeShop(await one(env.DB, 'SELECT * FROM shops WHERE id=?', id)) }, 201); }
  fail('ไม่พบคำขอ', 404);
}
export default { async fetch(req, env) { try { const u = new URL(req.url); if (u.pathname.startsWith('/api/')) return await api(req, env, u.pathname); return env.ASSETS.fetch(req); } catch (e) { return json({ error: e.message || 'ระบบขัดข้อง กรุณาลองใหม่' }, e.status || 500); } } };
